version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: GreenSathi
      MYSQL_PASSWORD: GreenSathi@990
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "3306:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
